### ISSUE TITLE
How add additional jar files to SparkContext

### ISSUE THREAD

**Issue by metasim** [Valassis-Digital-Media/spylon-kernel#46]
Is it possible with Spylon to add external jars to the initialized SparkContext, akin to the `%AddJar` in Toree or `import $ivy....` in Jupyter Scala?

**Comment by parente** [comment]
@metasim The standard Spark settings for referring to JARs and packages should work:

```
%%init_spark
launcher.jars = ["/some/local/path/to/a/file.jar"]
launcher.packages = ["maven:coordinates"]
```

There's no bells and whistles for pulling JARs from other sources, however. This is somewhat by design to keep the kernel a simple, bare bones option.

**Comment by metasim** [comment]
Oh wow, that's fantastic. Would you be interested in a PR for the README?

**Comment by parente** [comment]
Sure thing. Either way. Thanks!

**Comment by xsqian** [comment]
@parente I used `launcher.jars = ["mysql-connector-java-8.0.21.jar"]` according to your example, however, it still complains that `java.sql.SQLException: No suitable driver
  at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:105)`
do you have a working example? 
Thanks!

**Comment by damienlancry** [comment]
@parente I m using the spylon kernel and I would like to use the dependency pmml4s. as in your example I did 
```
%%init_spark
launcher.jars = ["pmml4s-spark_2.12-0.9.7.jar"]
launcher.packages = ["org.pmml4s:pmml4s-spark_2.12:0.9.7"]
```
followed by 
```
import org.pmml4s.spark.ScoreModel
```
but I am still getting the error 
```
<console>:29: error: object pmml4s is not a member of package org
       import org.pmml4s.spark.ScoreModel
```
any insight on what is going wrong?

EDIT: 
I don't know if it could be the root of the problem, but I think spylon uses scala 2.11 so I also tried:
```
%%init_spark
launcher.jars = ["pmml4s-spark_2.11-0.9.7.jar"]
launcher.packages = ["org.pmml4s:pmml4s-spark_2.11:0.9.7"]
```
with the right jar in a volume, but still got the same error

EDIT2:
Actually I think the spylon kernel I am using uses scala 2.12
```
util.Properties.versionString
[31]: res2: String = version 2.12.10
```

EDIT3: 
I also tried with 
```
%%init_spark
launcher.jars = ["file:/home/jovyan/pmml4s-spark_2.12-0.9.7.jar"]
launcher.packages = ["org.pmml4s:pmml4s-spark_2.12:0.9.7"]
```
and different combinations of everything above, but I don't know what is the exact syntax , a full working example would be 
amazing

EDIT4:
I managed to fix my issue by mounting the jars in a volume in another folder (/temporary/ instead of /home/jovyan/ ) (I am using the docker image)
